# Generated by Django 4.0 on 2021-12-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='reporter',
            field=models.CharField(blank=True, choices=[('lois-lane', 'Lois Lane'), ('clark-kent', 'Clark Kent'), ('jimmy-olson', 'Jimmy Olson')], max_length=255),
        ),
    ]
